import { describe, expect, it, vi, beforeEach } from "vitest";
import { appRouter } from "./routers";
import type { TrpcContext } from "./_core/context";
import { addAchievement, addEndingCollected } from "./db";

// Mock database functions
vi.mock("./db", () => ({
  upsertGameProgress: vi.fn().mockResolvedValue(undefined),
  getGameProgress: vi.fn().mockResolvedValue(null),
  getAllGameProgress: vi.fn().mockResolvedValue([]),
  addEndingCollected: vi.fn().mockResolvedValue(undefined),
  getEndingsCollected: vi.fn().mockResolvedValue([]),
  addAchievement: vi.fn().mockResolvedValue(undefined),
  getAchievements: vi.fn().mockResolvedValue([]),
  upsertUser: vi.fn().mockResolvedValue(undefined),
  getUserByOpenId: vi.fn().mockResolvedValue(undefined),
}));

beforeEach(() => {
  vi.clearAllMocks();
});

function createAuthContext(): TrpcContext {
  return {
    user: {
      id: 1,
      openId: "test-user-001",
      email: "test@example.com",
      name: "Test User",
      loginMethod: "manus",
      role: "user",
      createdAt: new Date(),
      updatedAt: new Date(),
      lastSignedIn: new Date(),
    },
    req: {
      protocol: "https",
      headers: {},
    } as TrpcContext["req"],
    res: {
      clearCookie: vi.fn(),
    } as unknown as TrpcContext["res"],
  };
}

describe("game.saveProgress", () => {
  it("saves game progress successfully", async () => {
    const ctx = createAuthContext();
    const caller = appRouter.createCaller(ctx);

    const result = await caller.game.saveProgress({
      gameId: "rainy-night",
      currentNodeId: 1,
      stats: { trust: 60, clues: 15, stress: 20 },
      history: [],
      isCompleted: false,
    });

    expect(result).toEqual({ success: true });
  });

  it("saves completed game progress with completedAt", async () => {
    const ctx = createAuthContext();
    const caller = appRouter.createCaller(ctx);

    const completedAt = new Date().toISOString();
    const result = await caller.game.saveProgress({
      gameId: "rainy-night",
      currentNodeId: 91,
      stats: { trust: 60, clues: 75, stress: 20 },
      history: [1],
      isCompleted: true,
      completedAt,
    });

    expect(result).toEqual({ success: true });
  });

  it("accepts synthetic deduction gate nodes generated by the client", async () => {
    const ctx = createAuthContext();
    const caller = appRouter.createCaller(ctx);

    const result = await caller.game.saveProgress({
      gameId: "rainy-night",
      currentNodeId: 900911,
      stats: { trust: 60, clues: 75, stress: 20 },
      history: [1, 900911],
      isCompleted: false,
    });

    expect(result).toEqual({ success: true });
  });

  it("rejects completed progress that does not point at an ending node", async () => {
    const ctx = createAuthContext();
    const caller = appRouter.createCaller(ctx);

    await expect(caller.game.saveProgress({
      gameId: "rainy-night",
      currentNodeId: 1,
      stats: { trust: 60, clues: 15, stress: 20 },
      history: [],
      isCompleted: true,
      completedAt: new Date().toISOString(),
    })).rejects.toThrow("Completed progress must point to an ending node");
  });

  it("rejects invalid stat keys", async () => {
    const ctx = createAuthContext();
    const caller = appRouter.createCaller(ctx);

    await expect(caller.game.saveProgress({
      gameId: "rainy-night",
      currentNodeId: 1,
      stats: { trust: 60, clues: 15, stress: 20, money: 999 },
      history: [],
      isCompleted: false,
    })).rejects.toThrow("Unknown stat key");
  });
});

describe("game.collectEnding", () => {
  it("records a collected ending", async () => {
    const ctx = createAuthContext();
    const caller = appRouter.createCaller(ctx);

    const result = await caller.game.collectEnding({
      gameId: "rainy-night",
      endingId: "truth",
      endingName: "伪造结局名",
    });

    expect(result).toEqual({ success: true });
    expect(vi.mocked(addEndingCollected)).toHaveBeenCalledWith(expect.objectContaining({
      gameId: "rainy-night",
      endingId: "truth",
      endingName: "真相大白",
    }));
  });

  it("rejects unknown endings", async () => {
    const ctx = createAuthContext();
    const caller = appRouter.createCaller(ctx);

    await expect(caller.game.collectEnding({
      gameId: "rainy-night",
      endingId: "fake-ending",
      endingName: "Fake Ending",
    })).rejects.toThrow("Unknown ending");
  });
});

describe("game.unlockAchievement", () => {
  it("unlocks an achievement", async () => {
    const ctx = createAuthContext();
    const caller = appRouter.createCaller(ctx);

    const result = await caller.game.unlockAchievement({
      achievementId: "first_ending",
    });

    expect(result).toEqual({ success: true });
  });

  it("unlocks generated ending achievements", async () => {
    const ctx = createAuthContext();
    const caller = appRouter.createCaller(ctx);

    const result = await caller.game.unlockAchievement({
      achievementId: "rainy-night_ending_truth",
    });

    expect(result).toEqual({ success: true });
    expect(vi.mocked(addAchievement)).toHaveBeenCalledWith(expect.objectContaining({
      achievementId: "rainy-night_ending_truth",
    }));
  });

  it("rejects unknown achievements", async () => {
    const ctx = createAuthContext();
    const caller = appRouter.createCaller(ctx);

    await expect(caller.game.unlockAchievement({
      achievementId: "fake_achievement",
    })).rejects.toThrow("Unknown achievement");
  });
});

describe("game.getProgress", () => {
  it("returns null when no progress exists", async () => {
    const ctx = createAuthContext();
    const caller = appRouter.createCaller(ctx);

    const result = await caller.game.getProgress({ gameId: "rainy-night" });
    expect(result).toBeNull();
  });
});

describe("game.getEndings", () => {
  it("returns empty array when no endings collected", async () => {
    const ctx = createAuthContext();
    const caller = appRouter.createCaller(ctx);

    const result = await caller.game.getEndings({});
    expect(result).toEqual([]);
  });
});

describe("game.getAchievements", () => {
  it("returns empty array when no achievements unlocked", async () => {
    const ctx = createAuthContext();
    const caller = appRouter.createCaller(ctx);

    const result = await caller.game.getAchievements();
    expect(result).toEqual([]);
  });
});

describe("game.getFullData", () => {
  it("returns combined progress, endings, and achievements", async () => {
    const ctx = createAuthContext();
    const caller = appRouter.createCaller(ctx);

    const result = await caller.game.getFullData();
    expect(result).toHaveProperty("progress");
    expect(result).toHaveProperty("endings");
    expect(result).toHaveProperty("achievements");
    expect(Array.isArray(result.progress)).toBe(true);
    expect(Array.isArray(result.endings)).toBe(true);
    expect(Array.isArray(result.achievements)).toBe(true);
  });
});
